[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base="dark"
primaryColor="#E0A14A"
backgroundColor="#121417"
secondaryBackgroundColor="#1B1F24"
textColor="#E8EDF2"
font="sans serif"

[client]
toolbarMode = "auto"

